### ISSUE TITLE
Error: {"status":"error","code":127} when trying to start server (this stage: Check if Server is Running Locally on Port 8000)

### ISSUE THREAD

**Issue by timuryung** [transformerlab/transformerlab-api#5]
OS: MacOS 14.3.1 (23D60), 
MacBook Air, 2020
CPU: Intel Core I3
<img width="582" alt="Screenshot 2024-02-21 at 21 26 36" src="https://github.com/transformerlab/transformerlab-api/assets/90114599/1cb79eba-6d31-40f9-a841-5396d2f25691">

**Comment by dadmobile** [comment]
For some reason uvicorn is not getting installed for some people. 
A possible workaround is to try manually running ~/.transformerlab/src/init.sh which should fix dependencies.

**Comment by timuryung** [comment]
Thank you very much! Please consider fix this error in the app, so people don't need to manually install everything.
